// jQuery RoyalSlider plugin. Custom build. Copyright 2011-2012 Dmitry Semenov http://dimsemenov.com 
// jquery.royalslider v9.3.3
(function(k){function u(b,f){var c=navigator.userAgent.toLowerCase(),g=k.browser,a=this,e=g.webkit||g.chrome;a.isIPAD=c.match(/(ipad)/);for(var d=document.createElement("div").style,i=["webkit","Moz","ms","O"],h="",j=0,m,c=0;c<i.length;c++)m=i[c],!h&&m+"Transform"in d&&(h=m),m=m.toLowerCase(),window.requestAnimationFrame||(window.requestAnimationFrame=window[m+"RequestAnimationFrame"],window.cancelAnimationFrame=window[m+"CancelAnimationFrame"]||window[m+"CancelRequestAnimationFrame"]);window.requestAnimationFrame||
(window.requestAnimationFrame=function(a){var b=(new Date).getTime(),c=Math.max(0,16-(b-j)),d=window.setTimeout(function(){a(b+c)},c);j=b+c;return d});window.cancelAnimationFrame||(window.cancelAnimationFrame=function(a){clearTimeout(a)});a.slider=k(b);a.ev=k(a);a._a=k(document);a.st=k.extend({},k.fn.royalSlider.defaults,f);a._b=a.st.transitionSpeed;a._c=0;if(a.st.allowCSS3&&(!e||a.st.allowCSS3OnWebkit))c=h+(h?"T":"t"),a._d=c+"ransform"in d&&c+"ransition"in d,a._d&&(a._e=h+(h?"P":"p")+"erspective"in
d);h=h.toLowerCase();a._f="-"+h+"-";a._g="vertical"===a.st.slidesOrientation?!1:!0;a._h=a._g?"left":"top";a._i=a._g?"width":"height";a._j=-1;a._k="fade"===a.st.transitionType?!1:!0;a._k||(a.st.sliderDrag=!1,a._l=10);a._m="z-index:0; display:none; opacity:0;";a._n=0;a._o=0;a._p=0;k.each(k.rsModules,function(b,c){c.call(a)});a.slides=[];a._q=0;(a.st.slides?k(a.st.slides):a.slider.children().detach()).each(function(){a._r(this,!0)});a.st.randomizeSlides&&a.slides.sort(function(){return 0.5-Math.random()});
a.numSlides=a.slides.length;a._s();a.st.startSlideId?a.st.startSlideId>a.numSlides-1&&(a.st.startSlideId=a.numSlides-1):a.st.startSlideId=0;a.staticSlideId=a.currSlideId=a._t=a.st.startSlideId;a.currSlide=a.slides[a.currSlideId];a._u=0;a.slider.addClass((a._g?"rsHor":"rsVer")+(a._k?"":" rsFade"));d='<div class="rsOverflow"><div class="rsContainer">';a.slidesSpacing=a.st.slidesSpacing;a._v=(a._g?a.slider.width():a.slider.height())+a.st.slidesSpacing;a._w=Boolean(0<a._x);1>=a.numSlides&&(a._y=!1);a._z=
a._y&&a._k?2===a.numSlides?1:2:0;a._a1=6>a.numSlides?a.numSlides:6;a._b1=0;a._c1=0;a.slidesJQ=[];for(c=0;c<a.numSlides;c++)a.slidesJQ.push(k('<div style="'+(a._k?"":c!==a.currSlideId?a._m:"z-index:0;")+'" class="rsSlide "></div>'));a._d1=d=k(d+"</div></div>");"ontouchstart"in window||"createTouch"in document?(a.hasTouch=!0,a._e1="touchstart.rs",a._f1="touchmove.rs",a._g1="touchend.rs",a._h1="touchcancel.rs",a._i1=0.5,a.st.sliderTouch&&(a._j1=!0)):(a.hasTouch=!1,a._i1=0.2,a.st.sliderDrag&&(a._j1=!0,
g.msie||g.opera?a._k1=a._l1="move":g.mozilla?(a._k1="-moz-grab",a._l1="-moz-grabbing"):e&&-1!=navigator.platform.indexOf("Mac")&&(a._k1="-webkit-grab",a._l1="-webkit-grabbing"),a._m1()),a._e1="mousedown.rs",a._f1="mousemove.rs",a._g1="mouseup.rs",a._h1="mouseup.rs");a.slider.html(d);a._n1=a.st.controlsInside?a._d1:a.slider;a._o1=a._d1.children(".rsContainer");a._p1=k('<div class="rsPreloader"></div>');g=a._o1.children(".rsSlide");a._q1=a.slidesJQ[a.currSlideId];a._r1=0;a._d?(a._s1="transition-property",
a._t1="transition-duration",a._u1="transition-timing-function",a._v1=a._w1=a._f+"transform",a._e?(e&&a.slider.addClass("rsWebkit3d"),a._x1="translate3d(",a._y1="px, ",a._z1="px, 0px)"):(a._x1="translate(",a._y1="px, ",a._z1="px)"),a._k?a._o1[a._f+a._s1]=a._f+"transform":(e={},e[a._f+a._s1]="opacity",e[a._f+a._t1]=a.st.transitionSpeed+"ms",e[a._f+a._u1]=a.st.css3easeInOut,g.css(e))):(a._w1="left",a._v1="top");var l;k(window).on("resize.rs",function(){l&&clearTimeout(l);l=setTimeout(function(){a.updateSliderSize()},
50)});a.ev.trigger("rsAfterPropsSetup");a.updateSliderSize();a.st.keyboardNavEnabled&&a._a2();a.st.arrowsNavHideOnTouch&&a.hasTouch&&(a.st.arrowsNav=!1);a.st.arrowsNav&&(e=a._n1,k('<div class="rsArrow rsArrowLeft"><div class="rsArrowIcn"></div></div><div class="rsArrow rsArrowRight"><div class="rsArrowIcn"></div></div>').appendTo(e),a._b2=e.children(".rsArrowLeft").click(function(b){b.preventDefault();a.prev()}),a._c2=e.children(".rsArrowRight").click(function(b){b.preventDefault();a.next()}),a.st.arrowsNavAutoHide&&
!a.hasTouch&&(a._b2.addClass("rsHidden"),a._c2.addClass("rsHidden"),e.one("mousemove.arrowshover",function(){a._b2.removeClass("rsHidden");a._c2.removeClass("rsHidden")}),e.hover(function(){a._d2||(a._b2.removeClass("rsHidden"),a._c2.removeClass("rsHidden"))},function(){a._d2||(a._b2.addClass("rsHidden"),a._c2.addClass("rsHidden"))})),a.ev.on("rsOnUpdateNav",function(){a._e2()}),a._e2());if(a._j1)a._o1.on(a._e1,function(b){a._f2(b)});else a.dragSuccess=!1;var r=["rsPlayBtnIcon","rsPlayBtn","rsCloseVideoBtn",
"rsCloseVideoIcn"];a._o1.click(function(b){if(!a.dragSuccess){var c=k(b.target).attr("class");if(-1!==k.inArray(c,r)&&a.toggleVideo())return!1;if(a.st.navigateByClick&&!a._g2){if(k(b.target).closest(".rsNoDrag",a._q1).length)return!0;a._h2(b)}a.ev.trigger("rsSlideClick")}}).on("click.rs","a",function(){if(a.dragSuccess)return!1;a._g2=!0;setTimeout(function(){a._g2=!1},3)});a.ev.trigger("rsAfterInit")}k.rsModules||(k.rsModules={});u.prototype={_h2:function(b){b=b[this._g?"pageX":"pageY"]-this._i2;
b>=this._p?this.next():0>b&&this.prev()},_s:function(){var b;b=this.st.numImagesToPreload;if(this._y=this.st.loop)2===this.numSlides?(this._y=!1,this.st.loopRewind=!0):2>this.numSlides&&(this.st.loopRewind=this._y=!1);this._y&&0<b&&(4>=this.numSlides?b=1:this.st.numImagesToPreload>(this.numSlides-1)/2&&(b=Math.floor((this.numSlides-1)/2)));this._x=b},_r:function(b,f){function c(a,b){b?e.images.push(a.attr(b)):e.images.push(a.text());if(i){i=!1;e.caption=!b?a.attr("alt"):a.contents();e.image=e.images[0];
e.videoURL=a.attr("data-rsVideo");var c=a.attr("data-rsw"),d=a.attr("data-rsh");"undefined"!==typeof c&&!1!==c&&"undefined"!==typeof d&&!1!==d?(e.iW=parseInt(c),e.iH=parseInt(d)):g.st.imgWidth&&g.st.imgHeight&&(e.iW=g.st.imgWidth,e.iH=g.st.imgHeight)}}var g=this,a,e={},d,i=!0,b=k(b);g._j2=b;g.ev.trigger("rsBeforeParseNode",[b,e]);if(!e.stopParsing)return b=g._j2,e.id=g._q,e.contentAdded=!1,g._q++,e.images=[],e.isBig=!1,e.hasCover||(b.hasClass("rsImg")?(d=b,a=!0):(d=b.find(".rsImg"),d.length&&(a=!0)),
a?(e.bigImage=d.eq(0).attr("data-rsBigImg"),d.each(function(){var a=k(this);a.is("a")?c(a,"href"):a.is("img")?c(a,"src"):c(a)})):b.is("img")&&(b.addClass("rsImg rsMainSlideImage"),c(b,"src"))),d=b.find(".rsCaption"),d.length&&(e.caption=d.remove()),e.content=b,g.ev.trigger("rsAfterParseNode",[b,e]),f&&g.slides.push(e),0===e.images.length&&(e.isLoaded=!0,e.isRendered=!1,e.isLoading=!1,e.images=null),e},_a2:function(){var b=this,f,c,g=function(a){37===a?b.prev():39===a&&b.next()};b._a.on("keydown.rskb",
function(a){if(!b._k2&&(c=a.keyCode,(37===c||39===c)&&!f))g(c),f=setInterval(function(){g(c)},700)}).on("keyup.rskb",function(){f&&(clearInterval(f),f=null)})},goTo:function(b,f){b!==this.currSlideId&&this._l2(b,this.st.transitionSpeed,!0,!f)},destroy:function(b){this.ev.trigger("rsBeforeDestroy");this._a.off("keydown.rskb keyup.rskb "+this._f1+" "+this._g1);this._o1.off(this._e1+" click");this.slider.data("royalSlider",null);k.removeData(this.slider,"royalSlider");k(window).off("resize.rs");b&&this.slider.remove();
this.ev=this.slider=this.slides=null},_m2:function(b,f){function c(c,e,f){c.isAdded?(g(e,c),a(e,c)):(f||(f=d.slidesJQ[e]),c.holder?f=c.holder:(f=d.slidesJQ[e]=k(f),c.holder=f),c.appendOnLoaded=!1,a(e,c,f),g(e,c),d._o2(c,f,b),appended=c.isAdded=!0)}function g(a,c){c.contentAdded||(d.setItemHtml(c,b),b||(c.contentAdded=!0))}function a(a,b,c){d._k&&(c||(c=d.slidesJQ[a]),c.css(d._h,(a+d._c1+r)*d._v))}function e(a){if(j){if(a>m-1)return e(a-m);if(0>a)return e(m+a)}return a}var d=this,i,h,j=d._y,m=d.numSlides;
if(!isNaN(f))return e(f);var l=d.currSlideId,r,n=b?Math.abs(d._n2-d.currSlideId)>=d.numSlides-1?0:1:d._x,p=Math.min(2,n),s=!1,t=!1,q;for(h=l;h<l+1+p;h++)if(q=e(h),(i=d.slides[q])&&(!i.isAdded||!i.positionSet)){s=!0;break}for(h=l-1;h>l-1-p;h--)if(q=e(h),(i=d.slides[q])&&(!i.isAdded||!i.positionSet)){t=!0;break}if(s)for(h=l;h<l+n+1;h++)q=e(h),r=Math.floor((d._t-(l-h))/d.numSlides)*d.numSlides,(i=d.slides[q])&&c(i,q);if(t)for(h=l-1;h>l-1-n;h--)q=e(h),r=Math.floor((d._t-(l-h))/m)*m,(i=d.slides[q])&&c(i,
q);if(!b){p=e(l-n);l=e(l+n);n=p>l?0:p;for(h=0;h<m;h++)if(!(p>l&&h>p-1)&&(h<n||h>l))if((i=d.slides[h])&&i.holder)i.holder.detach(),i.isAdded=!1}},setItemHtml:function(b,f){function c(){if(b.images){if(!b.isLoading){var a,c;b.content.hasClass("rsImg")?(a=b.content,c=!0):a=b.content.find(".rsImg:not(img)");a&&!a.is("img")&&a.each(function(){var a=k(this),d=k('<img class="rsImg" src="'+(a.is("a")?a.attr("href"):a.text())+'" />');c?b.content=d:a.replaceWith(d)});a=c?b.content:b.content.find("img.rsImg");
i();a.eq(0).addClass("rsMainSlideImage");b.iW&&b.iH&&(b.isLoaded||j._p2(b),e());b.isLoading=!0;if(b.isBig)k("<img />").on("load.rs error.rs",function(){g([this],!0)}).attr("src",b.image);else{b.loaded=[];b.imgLoaders=[];for(a=0;a<b.images.length;a++){var d=k("<img />");b.imgLoaders.push(this);d.on("load.rs error.rs",function(){b.loaded.push(this);b.loaded.length===b.imgLoaders.length&&g(b.loaded,!1)}).attr("src",b.images[a])}}}}else b.isRendered=!0,b.isLoaded=!0,b.isLoading=!1,e(!0)}function g(c,
d){if(c.length){var e=c[0];if(d!==b.isBig)(e=b.holder.children())&&1<e.length&&h();else if(b.iW&&b.iH)a();else if(b.iW=e.width,b.iH=e.height,b.iW&&b.iH)a();else{var f=new Image;f.onload=function(){f.width?(b.iW=f.width,b.iH=f.height,a()):setTimeout(function(){f.width&&(b.iW=f.width,b.iH=f.height);a()},1E3)};f.src=e.src}}else a()}function a(){b.isLoaded=!0;b.isLoading=!1;e();h();d()}function e(){if(!b.isAppended){var a=j.st.visibleNearby,c=b.id-j._n;if(!f&&!b.appendOnLoaded&&j.st.fadeinLoadedSlide&&
(0===c||(a||j._q2||j._k2)&&(-1===c||1===c)))b.content.css(j._f+"transition","opacity 400ms ease-in-out").css({visibility:"visible",opacity:0}),setTimeout(function(){b.content.css("opacity",1)},6);b.holder.find(".rsPreloader").length?b.holder.append(b.content):b.holder.html(b.content);b.isAppended=!0;b.isLoaded&&(j._p2(b),d());b.sizeReady||(b.sizeReady=!0,setTimeout(function(){j.ev.trigger("rsMaybeSizeReady",b)},100))}}function d(){b.loadedTriggered||(b.isLoaded=b.loadedTriggered=!0,b.holder.trigger("rsAfterContentSet"),
j.ev.trigger("rsAfterContentSet",b))}function i(){j.st.usePreloader&&b.holder.html(j._p1.clone())}function h(){if(j.st.usePreloader){var a=b.holder.find(".rsPreloader");a.length&&a.remove()}}var j=this;b.isLoaded?e():f?!j._k&&b.images&&b.iW&&b.iH?c():(b.holder.isWaiting=!0,i(),b.holder.slideId=-99):c()},_o2:function(b,f,c){var g=b.holder,a=b.id-this._n;this._k&&!c&&this.st.fadeinLoadedSlide&&(0===a||(this._q2||this._k2)&&(-1===a||1===a))?(f=b.content,f.css(this._f+"transition","opacity 400ms ease-in-out").css({visibility:"visible",
opacity:0}),this._o1.append(g),setTimeout(function(){f.css("opacity",1)},6)):this._o1.append(g);b.appendOnLoaded=!1},_f2:function(b,f){var c=this,g;c.ev.trigger("rsDragStart");if(k(b.target).closest(".rsNoDrag",c._q1).length)return c.dragSuccess=!1,!0;!f&&c._q2&&(c._r2=!0,c._s2());c.dragSuccess=!1;if(c._k2)c.hasTouch&&(c._t2=!0);else{c.hasTouch&&(c._t2=!1);c._u2();if(c.hasTouch){var a=b.originalEvent.touches;if(a&&0<a.length)g=a[0],1<a.length&&(c._t2=!0);else return}else g=b,b.preventDefault();c._k2=
!0;c._a.on(c._f1,function(a){c._v2(a,f)}).on(c._g1,function(a){c._w2(a,f)});c._x2="";c._y2=!1;c._z2=g.pageX;c._a3=g.pageY;c._b3=c._u=(!f?c._g:c._c3)?g.pageX:g.pageY;c._d3=0;c._e3=0;c._f3=!f?c._o:c._g3;c._h3=(new Date).getTime();if(c.hasTouch)c._d1.on(c._h1,function(a){c._w2(a,f)})}},_i3:function(b,f){if(this._j3){var c=this._k3,g=b.pageX-this._z2,a=b.pageY-this._a3,e=this._f3+g,d=this._f3+a,i=!f?this._g:this._c3,e=i?e:d,d=this._x2;this._y2=!0;this._z2=b.pageX;this._a3=b.pageY;"x"===d&&0!==g?this._d3=
0<g?1:-1:"y"===d&&0!==a&&(this._e3=0<a?1:-1);d=i?this._z2:this._a3;g=i?g:a;f?e>this._l3?e=this._f3+g*this._i1:e<this._m3&&(e=this._f3+g*this._i1):this._y||(0>=this.currSlideId&&0<d-this._b3&&(e=this._f3+g*this._i1),this.currSlideId>=this.numSlides-1&&0>d-this._b3&&(e=this._f3+g*this._i1));this._f3=e;200<c-this._h3&&(this._h3=c,this._u=d);f?this._o3(this._f3):this._k&&this._n3(this._f3)}},_v2:function(b,f){var c=this,g;if(c.hasTouch){if(c._p3)return;var a=b.originalEvent.touches;if(a){if(1<a.length)return;
g=a[0]}else return}else g=b;c._y2||(c._d&&(!f?c._o1:c._q3).css(c._f+c._t1,"0s"),function d(){c._k2&&(c._r3=requestAnimationFrame(d),c._s3&&c._i3(c._s3,f))}());if(c._j3)b.preventDefault(),c._k3=(new Date).getTime(),c._s3=g;else if(a=!f?c._g:c._c3,g=Math.abs(g.pageX-c._z2)-Math.abs(g.pageY-c._a3)-(a?-7:7),7<g){if(a)b.preventDefault(),c._x2="x";else if(c.hasTouch){c._t3();return}c._j3=!0}else if(-7>g){if(a){if(c.hasTouch){c._t3();return}}else b.preventDefault(),c._x2="y";c._j3=!0}},_t3:function(){this._p3=
!0;this._y2=this._k2=!1;this._w2()},_w2:function(b,f){function c(a){return 100>a?100:500<a?500:a}function g(b,d){if(a._k||f)i=(-a._t-a._c1)*a._v,h=Math.abs(a._o-i),a._b=h/d,b&&(a._b+=250),a._b=c(a._b),a._v3(i,!1)}var a=this,e,d,i,h;a.ev.trigger("rsDragRelease");a._s3=null;a._k2=!1;a._p3=!1;a._j3=!1;a._k3=0;cancelAnimationFrame(a._r3);a._y2&&(f?a._o3(a._f3):a._k&&a._n3(a._f3));a._a.off(a._f1).off(a._g1);a.hasTouch&&a._d1.off(a._h1);a._m1();if(!a._y2&&!a._t2&&f&&a._u3){var j=k(b.target).closest(".rsNavItem");
j.length&&a.goTo(j.index())}else{d=!f?a._g:a._c3;if(!a._y2||"y"===a._x2&&d||"x"===a._x2&&!d)if(!f&&a._r2){a._r2=!1;if(a.st.navigateByClick){a._h2(b);a.dragSuccess=!0;return}a.dragSuccess=!0}else{a._r2=!1;a.dragSuccess=!1;return}else a.dragSuccess=!0;a._r2=!1;a._x2="";var m=a.st.minSlideOffset;e=a.hasTouch?b.originalEvent.changedTouches[0]:b;var l=d?e.pageX:e.pageY,r=a._b3;e=a._u;var n=a.currSlideId,p=a.numSlides,s=d?a._d3:a._e3,t=a._y;Math.abs(l-r);e=l-e;d=(new Date).getTime()-a._h3;d=Math.abs(e)/
d;if(0===s||1>=p)g(!0,d);else{if(!t&&!f)if(0>=n){if(0<s){g(!0,d);return}}else if(n>=p-1&&0>s){g(!0,d);return}if(f){i=a._g3;if(i>a._l3)i=a._l3;else if(i<a._m3)i=a._m3;else{m=d*d/0.006;j=-a._g3;l=a._w3-a._x3+a._g3;0<e&&m>j?(j+=a._x3/(15/(0.003*(m/d))),d=d*j/m,m=j):0>e&&m>l&&(l+=a._x3/(15/(0.003*(m/d))),d=d*l/m,m=l);j=Math.max(Math.round(d/0.003),50);i+=m*(0>e?-1:1);if(i>a._l3){a._y3(i,j,!0,a._l3,200);return}if(i<a._m3){a._y3(i,j,!0,a._m3,200);return}}a._y3(i,j,!0)}else r+m<l?0>s?g(!1,d):a._l2("prev",
c(Math.abs(a._o-(-a._t-a._c1+1)*a._v)/d),!1,!0,!0):r-m>l?0<s?g(!1,d):a._l2("next",c(Math.abs(a._o-(-a._t-a._c1-1)*a._v)/d),!1,!0,!0):g(!1,d)}}},_n3:function(b){b=this._o=b;this._d?this._o1.css(this._w1,this._x1+(this._g?b+this._y1+0:0+this._y1+b)+this._z1):this._o1.css(this._g?this._w1:this._v1,b)},updateSliderSize:function(b){var f,c;if(this.st.autoScaleSlider){var g=this.st.autoScaleSliderWidth,a=this.st.autoScaleSliderHeight;this.st.autoScaleHeight?(f=this.slider.width(),f!=this.width&&(this.slider.css("height",
f*(a/g)),f=this.slider.width()),c=this.slider.height()):(c=this.slider.height(),c!=this.height&&(this.slider.css("width",c*(g/a)),c=this.slider.height()),f=this.slider.width())}else f=this.slider.width(),c=this.slider.height();if(b||f!=this.width||c!=this.height){this.width=f;this.height=c;this._z3=f;this._a4=c;this.ev.trigger("rsBeforeSizeSet");this.ev.trigger("rsAfterSizePropSet");this._d1.css({width:this._z3,height:this._a4});this._v=(this._g?this._z3:this._a4)+this.st.slidesSpacing;this._b4=this.st.imageScalePadding;
for(f=0;f<this.slides.length;f++)b=this.slides[f],b.positionSet=!1,b&&(b.images&&b.isLoaded)&&(b.isRendered=!1,this._p2(b));if(this._c4)for(f=0;f<this._c4.length;f++)b=this._c4[f],b.holder.css(this._h,(b.id+this._c1)*this._v);this._m2();this._k&&(this._d&&this._o1.css(this._f+"transition-duration","0s"),this._n3((-this._t-this._c1)*this._v));this.ev.trigger("rsOnUpdateNav")}this._i2=this._d1.offset();this._i2=this._i2[this._h]},appendSlide:function(b,f){var c=this._r(b);if(isNaN(f)||f>this.numSlides)f=
this.numSlides;this.slides.splice(f,0,c);this.slidesJQ.splice(f,0,'<div style="'+(this._k?"position:absolute;":this._m)+'" class="rsSlide"></div>');f<this.currSlideId&&this.currSlideId++;this.ev.trigger("rsOnAppendSlide",[c,f]);this._e4(f);f===this.currSlideId&&this.ev.trigger("rsAfterSlideChange")},removeSlide:function(b){var f=this.slides[b];f&&(f.holder&&f.holder.remove(),b<this.currSlideId&&this.currSlideId--,this.slides.splice(b,1),this.slidesJQ.splice(b,1),this.ev.trigger("rsOnRemoveSlide",
[b]),this._e4(b),b===this.currSlideId&&this.ev.trigger("rsAfterSlideChange"))},_e4:function(){var b=this,f=b.numSlides,f=0>=b._t?0:Math.floor(b._t/f);b.numSlides=b.slides.length;0===b.numSlides?(b.currSlideId=b._c1=b._t=0,b.currSlide=b._f4=null):b._t=f*b.numSlides+b.currSlideId;for(f=0;f<b.numSlides;f++)b.slides[f].id=f;b.currSlide=b.slides[b.currSlideId];b._q1=b.slidesJQ[b.currSlideId];b.currSlideId>=b.numSlides?b.goTo(b.numSlides-1):0>b.currSlideId&&b.goTo(0);b._s();b._k&&b._y&&b._o1.css(b._f+b._t1,
"0ms");b._g4&&clearTimeout(b._g4);b._g4=setTimeout(function(){b._k&&b._n3((-b._t-b._c1)*b._v);b._m2();b._k||b._q1.css({display:"block",opacity:1})},14);b.ev.trigger("rsOnUpdateNav")},_m1:function(){this._j1&&(!this.hasTouch&&this._k)&&(this._k1?this._d1.css("cursor",this._k1):(this._d1.removeClass("grabbing-cursor"),this._d1.addClass("grab-cursor")))},_u2:function(){this._j1&&(!this.hasTouch&&this._k)&&(this._l1?this._d1.css("cursor",this._l1):(this._d1.removeClass("grab-cursor"),this._d1.addClass("grabbing-cursor")))},
next:function(b){this._l2("next",this.st.transitionSpeed,!0,!b)},prev:function(b){this._l2("prev",this.st.transitionSpeed,!0,!b)},_l2:function(b,f,c,g,a){var e=this,d,i,h;e._i4&&e.stopVideo();e.ev.trigger("rsBeforeMove",[b,g]);newItemId="next"===b?e.currSlideId+1:"prev"===b?e.currSlideId-1:b=parseInt(b,10);if(!e._y){if(0>newItemId){e._j4("left",!g);return}if(newItemId>=e.numSlides){e._j4("right",!g);return}}e._q2&&(e._s2(),c=!1);i=newItemId-e.currSlideId;h=e._n2=e.currSlideId;var j=e.currSlideId+
i,g=e._t,m;e._y?(j=e._m2(!1,j),g+=i):g=j;e._n=j;e._f4=e.slidesJQ[e.currSlideId];e._t=g;e.currSlideId=e._n;e.currSlide=e.slides[e.currSlideId];e._q1=e.slidesJQ[e.currSlideId];j=Boolean(0<i);i=Math.abs(i);var l=Math.floor(h/e._x),k=Math.floor((h+(j?2:-2))/e._x),l=(j?Math.max(l,k):Math.min(l,k))*e._x+(j?e._x-1:0);l>e.numSlides-1?l=e.numSlides-1:0>l&&(l=0);h=j?l-h:h-l;h>e._x&&(h=e._x);if(i>h+2){e._c1+=(i-(h+2))*(j?-1:1);f*=1.4;for(h=0;h<e.numSlides;h++)e.slides[h].positionSet=!1}e._b=f;e._m2(!0);a||(m=
!0);d=(-g-e._c1)*e._v;m?setTimeout(function(){e._h4=!1;e._v3(d,b,!1,c);e.ev.trigger("rsOnUpdateNav")},0):(e._v3(d,b,!1,c),e.ev.trigger("rsOnUpdateNav"))},_e2:function(){this.st.arrowsNav&&(1>=this.numSlides?(this._b2.css("display","none"),this._c2.css("display","none")):(this._b2.css("display","block"),this._c2.css("display","block"),!this._y&&!this.st.loopRewind&&(0===this.currSlideId?this._b2.addClass("rsArrowDisabled"):this._b2.removeClass("rsArrowDisabled"),this.currSlideId===this.numSlides-1?
this._c2.addClass("rsArrowDisabled"):this._c2.removeClass("rsArrowDisabled"))))},_v3:function(b,f,c,g,a){function e(){var a;if(i&&(a=i.data("rsTimeout")))i!==h&&i.css({opacity:0,display:"none",zIndex:0}),clearTimeout(a),i.data("rsTimeout","");if(a=h.data("rsTimeout"))clearTimeout(a),h.data("rsTimeout","")}var d=this,i,h,j={};isNaN(d._b)&&(d._b=400);d._o=d._f3=b;d.ev.trigger("rsBeforeAnimStart");d._d?d._k?(d._b=parseInt(d._b),j[d._f+d._t1]=d._b+"ms",j[d._f+d._u1]=g?k.rsCSS3Easing[d.st.easeInOut]:k.rsCSS3Easing[d.st.easeOut],
d._o1.css(j),g||!d.hasTouch?setTimeout(function(){d._n3(b)},5):d._n3(b)):(d._b=d.st.transitionSpeed,i=d._f4,h=d._q1,h.data("rsTimeout")&&h.css("opacity",0),e(),i&&i.data("rsTimeout",setTimeout(function(){j[d._f+d._t1]="0ms";j.zIndex=0;j.display="none";i.data("rsTimeout","");i.css(j);setTimeout(function(){i.css("opacity",0)},16)},d._b+60)),j.display="block",j.zIndex=d._l,j.opacity=0,j[d._f+d._t1]="0ms",j[d._f+d._u1]=k.rsCSS3Easing[d.st.easeInOut],h.css(j),h.data("rsTimeout",setTimeout(function(){h.css(d._f+
d._t1,d._b+"ms");h.data("rsTimeout",setTimeout(function(){h.css("opacity",1);h.data("rsTimeout","")},20))},20))):d._k?(j[d._g?d._w1:d._v1]=b+"px",d._o1.animate(j,d._b,g?d.st.easeInOut:d.st.easeOut)):(i=d._f4,h=d._q1,h.stop(!0,!0).css({opacity:0,display:"block",zIndex:d._l}),d._b=d.st.transitionSpeed,h.animate({opacity:1},d._b,d.st.easeInOut),e(),i&&i.data("rsTimeout",setTimeout(function(){i.stop(!0,!0).css({opacity:0,display:"none",zIndex:0})},d._b+60)));d._q2=!0;d.loadingTimeout&&clearTimeout(d.loadingTimeout);
d.loadingTimeout=a?setTimeout(function(){d.loadingTimeout=null;a.call()},d._b+60):setTimeout(function(){d.loadingTimeout=null;d._k4(f)},d._b+60)},_s2:function(){this._q2=!1;clearTimeout(this.loadingTimeout);if(this._k)if(this._d){var b=this._o,f=this._f3=this._l4();this._o1.css(this._f+this._t1,"0ms");b!==f&&this._n3(f)}else this._o1.stop(!0),this._o=parseInt(this._o1.css(this._w1),10);else 20<this._l?this._l=10:this._l++},_l4:function(){var b=window.getComputedStyle(this._o1.get(0),null).getPropertyValue(this._f+
"transform").replace(/^matrix\(/i,"").split(/, |\)$/g);return parseInt(b[this._g?4:5],10)},_m4:function(b,f){return this._d?this._x1+(f?b+this._y1+0:0+this._y1+b)+this._z1:b},_k4:function(){this._k||(this._q1.css("z-index",0),this._l=10);this._q2=!1;this.staticSlideId=this.currSlideId;this._m2();this._n4=!1;this.ev.trigger("rsAfterSlideChange")},_j4:function(b,f){var c=this,g=(-c._t-c._c1)*c._v;if(!(0===c.numSlides||c._q2))if(c.st.loopRewind)c.goTo("left"===b?c.numSlides-1:0,f);else if(c._k){c._b=
200;var a=function(){c._q2=!1};c._v3(g+("left"===b?30:-30),"",!1,!0,function(){c._q2=!1;c._v3(g,"",!1,!0,a)})}},_p2:function(b){if(!b.isRendered){var f=b.content,c="rsMainSlideImage",g,a=this.st.imageAlignCenter,e=this.st.imageScaleMode,d;b.videoURL&&(c="rsVideoContainer","fill"!==e?g=!0:(d=f,d.hasClass(c)||(d=d.find("."+c)),d.css({width:"100%",height:"100%"}),c="rsMainSlideImage"));f.hasClass(c)||(f=f.find("."+c));if(f){var i=b.iW,c=b.iH;b.isRendered=!0;if("none"!==e||a){bMargin="fill"!==e?this._b4:
0;b=this._z3-2*bMargin;d=this._a4-2*bMargin;var h,j,k={};if("fit-if-smaller"===e&&(i>b||c>d))e="fit";if("fill"===e||"fit"===e)h=b/i,j=d/c,h="fill"==e?h>j?h:j:"fit"==e?h<j?h:j:1,i=Math.ceil(i*h,10),c=Math.ceil(c*h,10);"none"!==e&&(k.width=i,k.height=c,g&&f.find(".rsImg").css({width:"100%",height:"100%"}));a&&(k.marginLeft=Math.floor((b-i)/2)+bMargin,k.marginTop=Math.floor((d-c)/2)+bMargin);f.css(k)}}}}};k.rsProto=u.prototype;k.fn.royalSlider=function(b){var f=arguments;return this.each(function(){var c=
k(this);if("object"===typeof b||!b)c.data("royalSlider")||c.data("royalSlider",new u(c,b));else if((c=c.data("royalSlider"))&&c[b])return c[b].apply(c,Array.prototype.slice.call(f,1))})};k.fn.royalSlider.defaults={slidesSpacing:8,startSlideId:0,loop:!1,loopRewind:!1,numImagesToPreload:4,fadeinLoadedSlide:!0,slidesOrientation:"horizontal",transitionType:"move",transitionSpeed:600,controlNavigation:"bullets",controlsInside:!0,arrowsNav:!0,arrowsNavAutoHide:!0,navigateByClick:!0,randomizeSlides:!1,sliderDrag:!0,
sliderTouch:!0,keyboardNavEnabled:!1,fadeInAfterLoaded:!0,allowCSS3:!0,allowCSS3OnWebkit:!0,addActiveClass:!1,autoHeight:!1,easeOut:"easeOutSine",easeInOut:"easeInOutSine",minSlideOffset:10,imageScaleMode:"fit-if-smaller",imageAlignCenter:!0,imageScalePadding:4,usePreloader:!0,autoScaleSlider:!1,autoScaleSliderWidth:800,autoScaleSliderHeight:400,autoScaleHeight:!0,arrowsNavHideOnTouch:!1,globalCaption:!1};k.rsCSS3Easing={easeOutSine:"cubic-bezier(0.390, 0.575, 0.565, 1.000)",easeInOutSine:"cubic-bezier(0.445, 0.050, 0.550, 0.950)"};
k.extend(jQuery.easing,{easeInOutSine:function(b,f,c,g,a){return-g/2*(Math.cos(Math.PI*f/a)-1)+c},easeOutSine:function(b,f,c,g,a){return g*Math.sin(f/a*(Math.PI/2))+c},easeOutCubic:function(b,f,c,g,a){return g*((f=f/a-1)*f*f+1)+c}})})(jQuery,window);
// jquery.rs.deeplinking v1.0.4 + jQuery hashchange plugin v1.3 Copyright (c) 2010
(function(a){a.extend(a.rsProto,{_o5:function(){var b=this,g,c,e;b._p5={enabled:!1,change:!1,prefix:""};b.st.deeplinking=a.extend({},b._p5,b.st.deeplinking);if(b.st.deeplinking.enabled){var h=b.st.deeplinking.change,d="#"+b.st.deeplinking.prefix,f=function(){var a=window.location.hash;return a&&(a=parseInt(a.substring(d.length),10),0<=a)?a-1:-1},i=f();-1!==i&&(b.st.startSlideId=i);h&&(a(window).on("hashchange.rs",function(){if(!g){var a=f();0>a||(a>b.numSlides-1&&(a=b.numSlides-1),b.goTo(a))}}),b.ev.on("rsBeforeAnimStart",
function(){c&&clearTimeout(c);e&&clearTimeout(e)}),b.ev.on("rsAfterSlideChange",function(){c&&clearTimeout(c);e&&clearTimeout(e);e=setTimeout(function(){g=!0;window.location.hash=d+(b.currSlideId+1);c=setTimeout(function(){g=!1;c=null},60)},400)}));b.ev.on("rsBeforeDestroy",function(){c=e=null;h&&a(window).off("hashchange.rs")})}}});a.rsModules.deeplinking=a.rsProto._o5})(jQuery);
(function(a,b,g){function c(a){a=a||location.href;return"#"+a.replace(/^[^#]*#?(.*)$/,"$1")}"$:nomunge";var e=document,h,d=a.event.special,f=e.documentMode,i="onhashchange"in b&&(f===g||7<f);a.fn.hashchange=function(a){return a?this.bind("hashchange",a):this.trigger("hashchange")};a.fn.hashchange.delay=50;d.hashchange=a.extend(d.hashchange,{setup:function(){if(i)return!1;a(h.start)},teardown:function(){if(i)return!1;a(h.stop)}});var n=function(){var e=c(),d=q(m);e!==m?(p(m=e,d),a(b).trigger("hashchange")):
d!==m&&(location.href=location.href.replace(/#.*/,"")+d);k=setTimeout(n,a.fn.hashchange.delay)},d={},k,m=c(),p=f=function(a){return a},q=f;d.start=function(){k||n()};d.stop=function(){k&&clearTimeout(k);k=g};if(a.browser.msie&&!i){var j,l;d.start=function(){j||(l=(l=a.fn.hashchange.src)&&l+c(),j=a('<iframe tabindex="-1" title="empty"/>').hide().one("load",function(){l||p(c());n()}).attr("src",l||"javascript:0").insertAfter("body")[0].contentWindow,e.onpropertychange=function(){try{"title"===event.propertyName&&
(j.document.title=e.title)}catch(a){}})};d.stop=f;q=function(){return c(j.location.href)};p=function(b,d){var c=j.document,f=a.fn.hashchange.domain;b!==d&&(c.title=e.title,c.open(),f&&c.write('<script>document.domain="'+f+'"<\/script>'),c.close(),j.location.hash=b)}}h=d})(jQuery,this);
